// AzkaCraft — daily "Word of the Day" + "Fun Fact" content.
// 300 entries each, shown in a fixed sequential order (not random) and
// advancing once per day at midnight WIB (UTC+7) — so every kid looking
// at the app on the same calendar day (Jakarta time) sees the same pair.
// After 300 days the cycle repeats from the top.

const WORDS_OF_DAY = [
  ["Whimsical", "playfully odd"],
  ["Brave", "not afraid of danger"],
  ["Curious", "eager to learn or know"],
  ["Enormous", "very, very big"],
  ["Gentle", "kind and soft"],
  ["Joyful", "full of happiness"],
  ["Clever", "quick at learning things"],
  ["Silent", "making no sound"],
  ["Radiant", "shining brightly"],
  ["Cozy", "warm and comfortable"],
  ["Sturdy", "strong and well built"],
  ["Tiny", "very small"],
  ["Vast", "extremely large in area"],
  ["Cheerful", "happy and bright"],
  ["Mysterious", "hard to understand or explain"],
  ["Nimble", "quick and light in movement"],
  ["Ancient", "very old, from long ago"],
  ["Fragile", "easily broken"],
  ["Generous", "willing to give and share"],
  ["Humble", "not proud or boastful"],
  ["Loyal", "always faithful to someone"],
  ["Peculiar", "strange or unusual"],
  ["Quaint", "charmingly old-fashioned"],
  ["Resilient", "able to recover quickly"],
  ["Serene", "calm and peaceful"],
  ["Timid", "shy and easily frightened"],
  ["Unique", "the only one of its kind"],
  ["Vivid", "bright and full of life"],
  ["Wander", "to walk around without a plan"],
  ["Zealous", "full of enthusiasm"],
  ["Adventure", "an exciting journey or experience"],
  ["Bashful", "shy in a shy, sweet way"],
  ["Courageous", "brave in a difficult situation"],
  ["Dazzling", "so bright it amazes you"],
  ["Eager", "wanting to do something very much"],
  ["Fabulous", "wonderful, amazing"],
  ["Giggle", "to laugh in a light, silly way"],
  ["Harmony", "different parts fitting together nicely"],
  ["Inspire", "to fill someone with an idea to act"],
  ["Jolly", "full of happy, festive feeling"],
  ["Kindred", "similar in nature, related"],
  ["Lively", "full of energy"],
  ["Marvel", "to feel wonder and admiration"],
  ["Nurture", "to care for and help grow"],
  ["Optimistic", "hopeful about the future"],
  ["Playful", "full of fun, not serious"],
  ["Quest", "a long search for something"],
  ["Rejoice", "to feel or show great joy"],
  ["Sparkle", "to shine with tiny flashes of light"],
  ["Triumph", "a great victory or achievement"],
  ["Unwavering", "staying firm, not changing"],
  ["Valiant", "showing great courage"],
  ["Wonder", "a feeling of surprise and admiration"],
  ["Yearn", "to want something very much"],
  ["Zest", "great enthusiasm and energy"],
  ["Abundant", "existing in large amounts"],
  ["Blossom", "to grow and flourish, like a flower"],
  ["Cascade", "a small waterfall falling in stages"],
  ["Delight", "great pleasure"],
  ["Enchant", "to fill with delight, as if by magic"],
  ["Flourish", "to grow well and thrive"],
  ["Glimmer", "a faint or unsteady light"],
  ["Hush", "a stillness or silence"],
  ["Illuminate", "to light something up"],
  ["Jubilant", "feeling great happiness and triumph"],
  ["Keen", "having a strong interest or feeling"],
  ["Lantern", "a case that holds a light"],
  ["Melody", "a pleasant tune of musical notes"],
  ["Nourish", "to keep someone healthy with food"],
  ["Oasis", "a green, fertile spot in a desert"],
  ["Pinnacle", "the highest point of something"],
  ["Quiver", "to shake with a slight trembling motion"],
  ["Ripple", "a small wave on water's surface"],
  ["Shimmer", "to shine with a soft, wavering light"],
  ["Tranquil", "free from disturbance, calm"],
  ["Universe", "everything that exists in space"],
  ["Vibrant", "full of energy and bright color"],
  ["Whisper", "to speak very softly and quietly"],
  ["Yonder", "at a distance, over there"],
  ["Zephyr", "a soft, gentle breeze"],
  ["Astonish", "to surprise someone greatly"],
  ["Buoyant", "able to float, or cheerful"],
  ["Compassion", "caring about others' feelings"],
  ["Diligent", "working hard and carefully"],
  ["Elegant", "graceful and stylish"],
  ["Fascinate", "to attract and hold interest"],
  ["Grateful", "feeling thankful"],
  ["Honest", "always telling the truth"],
  ["Imagine", "to form a picture in your mind"],
  ["Journey", "an act of traveling somewhere"],
  ["Kindle", "to start a fire, or spark a feeling"],
  ["Legacy", "something passed down from before"],
  ["Miracle", "an amazing, wonderful happening"],
  ["Nostalgia", "a warm longing for the past"],
  ["Overcome", "to succeed in dealing with a problem"],
  ["Patient", "able to wait calmly"],
  ["Quiet", "making very little noise"],
  ["Reliable", "able to be trusted"],
  ["Sincere", "genuine, honest feeling"],
  ["Thoughtful", "showing careful thought for others"],
  ["Unite", "to come together as one"],
  ["Effervesce", "to bubble with excitement"],
  ["Wisdom", "knowledge gained from experience"],
  ["Xylophone", "an instrument played by striking wooden bars"],
  ["Yield", "to produce or give way to"],
  ["Zenith", "the highest point reached"],
  ["Aspire", "to have a strong hope or ambition"],
  ["Breeze", "a gentle wind"],
  ["Charm", "a quality that delights others"],
  ["Discover", "to find something for the first time"],
  ["Endure", "to keep going through hardship"],
  ["Frolic", "to play and move about joyfully"],
  ["Glisten", "to shine with a sparkling light"],
  ["Harvest", "the gathering of ripe crops"],
  ["Innovate", "to introduce something new"],
  ["Voyage", "a long trip, especially by sea"],
  ["Kinship", "a close connection between people"],
  ["Luminous", "giving off light, glowing"],
  ["Mellow", "soft, smooth, and relaxed"],
  ["Nestle", "to settle comfortably into a space"],
  ["Ordinary", "normal, not special or unusual"],
  ["Ponder", "to think carefully about something"],
  ["Quirky", "unusual in a charming way"],
  ["Radiate", "to send out light or warmth"],
  ["Soothe", "to gently calm someone"],
  ["Treasure", "something very precious"],
  ["Uplift", "to raise someone's spirits"],
  ["Venture", "a risky or daring journey"],
  ["Wholesome", "good for your health and mind"],
  ["Amenable", "willing to go along with something"],
  ["Zany", "funny in a wild, silly way"],
  ["Alert", "quick to notice things"],
  ["Bond", "a close connection between people"],
  ["Cherish", "to hold something dear"],
  ["Dawn", "the first light of morning"],
  ["Embark", "to start a journey"],
  ["Fond", "having a liking for something"],
  ["Glow", "to shine with a soft steady light"],
  ["Haven", "a safe place"],
  ["Ignite", "to set something on fire, spark"],
  ["Jubilee", "a special anniversary celebration"],
  ["Keepsake", "an object kept to remember someone"],
  ["Linger", "to stay somewhere a little longer"],
  ["Muse", "to think deeply about something"],
  ["Nook", "a small, cozy corner"],
  ["Opal", "a gemstone with shifting colors"],
  ["Pristine", "clean and untouched"],
  ["Quench", "to satisfy your thirst"],
  ["Roam", "to wander freely"],
  ["Sanctuary", "a place of safety or peace"],
  ["Twilight", "the soft light after sunset"],
  ["Umbrella", "a cover you hold to keep off rain"],
  ["Colossal", "huge in size or amount"],
  ["Wonderous", "causing feelings of wonder"],
  ["Xenial", "friendly to guests and strangers"],
  ["Youthful", "full of the energy of youth"],
  ["Zeal", "great energy for a cause or goal"],
  ["Amaze", "to fill with great surprise"],
  ["Blissful", "extremely happy"],
  ["Comrade", "a close companion or friend"],
  ["Dexterous", "skillful with your hands"],
  ["Ecstatic", "overwhelmingly happy"],
  ["Fervent", "having very strong feelings"],
  ["Glee", "great delight or joy"],
  ["Heritage", "traditions passed from ancestors"],
  ["Idyllic", "extremely peaceful and picturesque"],
  ["Jest", "a playful joke"],
  ["Keenness", "eagerness or sharpness of interest"],
  ["Lush", "growing thickly and richly"],
  ["Majestic", "grand and impressive"],
  ["Nimbly", "quickly and lightly, with agility"],
  ["Oblige", "to help someone kindly"],
  ["Placid", "calm and peaceful"],
  ["Quibble", "to argue about small, unimportant things"],
  ["Robust", "strong and healthy"],
  ["Solace", "comfort in a time of sadness"],
  ["Affectionate", "gentle and caring"],
  ["Unfurl", "to open out fully, like a sail"],
  ["Vigor", "energy and strength"],
  ["Wistful", "having a quiet, thoughtful longing"],
  ["Xerox", "to make a photocopy of something"],
  ["Afar", "over there, in that direction"],
  ["Zodiac", "the band of constellations used in astrology"],
  ["Amble", "to walk at a slow, easy pace"],
  ["Bountiful", "abundant, plentiful"],
  ["Candid", "truthful and straightforward"],
  ["Dapper", "neat and stylishly dressed"],
  ["Effervescent", "bubbly and full of enthusiasm"],
  ["Frugal", "careful about spending"],
  ["Gallant", "brave and honorable"],
  ["Hearty", "warm and friendly, or nourishing"],
  ["Intrepid", "fearless and adventurous"],
  ["Jovial", "cheerful and friendly"],
  ["Keepsafe", "something kept safe with care"],
  ["Limber", "flexible, able to bend easily"],
  ["Merry", "cheerful and lighthearted"],
  ["Novel", "new and original"],
  ["Opulent", "richly luxurious"],
  ["Poised", "calm, graceful, and in control"],
  ["Expedition", "a journey to search for something"],
  ["Rustic", "simple, plain, in a country style"],
  ["Spirited", "full of energy and courage"],
  ["Tenacious", "holding firmly to a purpose"],
  ["Untamed", "wild, not controlled"],
  ["Vivacious", "attractively lively and animated"],
  ["Whimsy", "a playful or fanciful idea"],
  ["Xenophile", "someone who loves other cultures"],
  ["Pliant", "flexible, giving way gently"],
  ["Zealot", "a person with intense enthusiasm"],
  ["Amiable", "friendly and pleasant"],
  ["Benevolent", "kind and generous"],
  ["Captivate", "to attract and hold interest"],
  ["Delicate", "fine, easily damaged, gentle"],
  ["Exquisite", "extremely beautiful and detailed"],
  ["Frolicsome", "playful and full of fun"],
  ["Genuine", "real, authentic"],
  ["Placidity", "peaceful and happy, calm"],
  ["Immerse", "to become fully involved"],
  ["Jaunty", "cheerful and lively in manner"],
  ["Kaleidoscope", "a pattern of always-changing colors"],
  ["Luster", "a soft shine or glow"],
  ["Mirthful", "full of joyful laughter"],
  ["Nautical", "relating to ships and the sea"],
  ["Oblivious", "not aware of what's happening"],
  ["Immaculate", "spotless and unspoiled"],
  ["Quixotic", "idealistic in an unrealistic way"],
  ["Resolute", "firm and determined"],
  ["Serendipity", "a pleasant surprise found by chance"],
  ["Tumble", "to fall or roll clumsily"],
  ["Utopia", "an imagined perfect place"],
  ["Vagabond", "a wanderer with no fixed home"],
  ["Whittle", "to carve wood into shape"],
  ["Xylograph", "a picture carved into wood"],
  ["Distant", "far away, at a distance"],
  ["Zealously", "with great energy and enthusiasm"],
  ["Affable", "friendly and easy to talk to"],
  ["Blithe", "cheerful and carefree"],
  ["Contented", "satisfied and happy"],
  ["Doting", "showing great love and care"],
  ["Effortless", "done easily, without struggle"],
  ["Frisky", "playful and full of energy"],
  ["Gregarious", "sociable, enjoying company"],
  ["Hopeful", "feeling positive about the future"],
  ["Ingenious", "very clever and inventive"],
  ["Elated", "expressing great happiness"],
  ["Kindly", "in a friendly, gentle way"],
  ["Lucid", "clear and easy to understand"],
  ["Meander", "to wander slowly along a winding path"],
  ["Nifty", "clever and useful"],
  ["Ornate", "decorated in an elaborate way"],
  ["Perceptive", "quick to notice or understand"],
  ["Quicken", "to make something happen faster"],
  ["Beaming", "glowing with light or happiness"],
  ["Steadfast", "firmly loyal or unchanging"],
  ["Caring", "showing gentle, loving care"],
  ["Undaunted", "not discouraged by difficulty"],
  ["Vigilant", "watchful and alert"],
  ["Nutritious", "healthy and good"],
  ["Xenon", "a colorless, odorless gas"],
  ["Yielded", "gave way or produced something"],
  ["Zephyrous", "having a soft, gentle wind"],
  ["Agile", "able to move quickly and easily"],
  ["Bloom", "to produce flowers, or thrive"],
  ["Chivalrous", "courteous and honorable"],
  ["Diligence", "careful and steady effort"],
  ["Effulgent", "shining brightly, radiant"],
  ["Frank", "honest and direct in speech"],
  ["Graceful", "moving in a smooth, elegant way"],
  ["Hallow", "to honor as holy or sacred"],
  ["Illustrious", "well known and admired"],
  ["Jocund", "cheerful and lighthearted"],
  ["Astute", "eager and sharp-minded"],
  ["Loquacious", "very talkative"],
  ["Mirage", "an optical illusion caused by heat"],
  ["Nimbus", "a glowing halo of light"],
  ["Obliging", "willing to help others"],
  ["Prudent", "careful and sensible in decisions"],
  ["Picturesque", "attractively unusual or old-fashioned"],
  ["Rapport", "a close, understanding relationship"],
  ["Sagacious", "having good judgment, wise"],
  ["Tactful", "careful not to upset others"],
  ["Unassuming", "modest, not showing off"],
  ["Verdant", "green with grass or trees"],
  ["Wary", "cautious about possible danger"],
  ["Xanadu", "an idyllic, beautiful place"],
  ["Horizon", "the line where earth meets sky, far away"],
  ["Zestful", "full of energy and enjoyment"],
  ["Amity", "friendship, peaceful relations"],
  ["Beacon", "a light or signal for guidance"],
  ["Cordial", "warm and friendly"],
  ["Diaphanous", "light and delicate, almost see-through"],
  ["Effuse", "to pour out feelings freely"],
  ["Frisson", "a sudden thrill of excitement"],
  ["Gossamer", "very light and delicate, like a spiderweb"],
  ["Untroubled", "calm, happy, and peaceful"],
  ["Incandescent", "glowing with intense heat or light"],
  ["Jocular", "fond of joking, playful"],
  ["Kismet", "fate or destiny"],
  ["Lissome", "slender and graceful in movement"],
  ["Mellifluous", "sweet and smooth sounding"]
];

const FUN_FACTS = [
  "The ocean covers over 70% of our whole planet!",
  "A group of flamingos is called a flamboyance.",
  "Honey never spoils — archaeologists have found edible honey in ancient tombs.",
  "Octopuses have three hearts and blue blood.",
  "A day on Venus is longer than a year on Venus.",
  "Bananas are berries, but strawberries are not!",
  "Sharks existed before trees appeared on Earth.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "A bolt of lightning is hotter than the surface of the sun.",
  "Elephants are the only animals that can't jump.",
  "The Eiffel Tower can grow taller in summer heat.",
  "Butterflies taste with their feet.",
  "A snail can sleep for three years.",
  "The Great Wall of China is not actually visible from space with the naked eye.",
  "Some turtles can breathe through their bottoms.",
  "A single cloud can weigh more than a million pounds.",
  "Wombat poop is cube-shaped.",
  "There are more stars in the universe than grains of sand on all beaches on Earth.",
  "Cows have best friends and get stressed when separated.",
  "A group of crows is called a murder.",
  "The heart of a shrimp is located in its head.",
  "Polar bears have black skin under their white fur.",
  "It rains diamonds on Saturn and Jupiter.",
  "The tongue of a blue whale weighs as much as an elephant.",
  "Koalas have fingerprints so similar to humans they can confuse crime scenes.",
  "The Sahara Desert can get snow sometimes.",
  "Some fish can change their sex during their lifetime.",
  "A rainbow can only be seen in the morning or late afternoon.",
  "There are more possible chess games than atoms in the universe.",
  "Kangaroos cannot walk backward.",
  "The shortest war in history lasted only 38 minutes.",
  "A group of pandas is called an embarrassment.",
  "Venus is the hottest planet in our solar system.",
  "Starfish don't have brains or blood.",
  "The first oranges weren't orange — they were green!",
  "A shrimp's heart is in its head.",
  "Some volcanoes shoot out blue lava at night.",
  "Cats can't taste sweetness.",
  "The Antarctic ice sheet holds most of the world's fresh water.",
  "Giraffes only need 5 to 30 minutes of sleep a day.",
  "The moon is slowly moving away from Earth every year.",
  "A jellyfish is 95% water.",
  "Woodpeckers can peck 20 times a second.",
  "The inventor of the frisbee was turned into a frisbee after he died.",
  "A single strand of spaghetti is called a spaghetto.",
  "Some ancient Roman coins were used as toothpaste ingredients.",
  "Penguins propose to their mates with a pebble.",
  "The dot over a lowercase 'i' or 'j' is called a tittle.",
  "Hot water can freeze faster than cold water in certain conditions.",
  "There's a species of jellyfish that is biologically immortal.",
  "Slugs have four noses.",
  "The Statue of Liberty's official name is 'Liberty Enlightening the World.'",
  "A crocodile can't stick its tongue out.",
  "Human bones are stronger than steel, pound for pound.",
  "The average cloud weighs around a million pounds.",
  "Cows produce more milk when listening to music.",
  "There's enough gold in the Earth's core to coat the entire planet.",
  "The world's largest desert is actually Antarctica, not the Sahara.",
  "A hummingbird's heart beats up to 1,260 times a minute.",
  "Cheetahs can't roar — they chirp like birds.",
  "Some plants can 'hear' the sound of water and grow toward it.",
  "An octopus can taste through its suckers.",
  "The unicorn is the national animal of Scotland.",
  "Bees can recognize human faces.",
  "The tallest mountain in the solar system is on Mars — Olympus Mons.",
  "It takes about 8 minutes for sunlight to reach Earth.",
  "Some snails can regrow their eyes.",
  "The longest recorded flight of a chicken is about 13 seconds.",
  "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
  "Dolphins have names for each other made of unique whistles.",
  "The world's smallest reptile was discovered in Madagascar and fits on a fingertip.",
  "Human noses can remember 50,000 different scents.",
  "A crocodile's bite is one of the strongest in the animal kingdom.",
  "Mount Everest grows about 4mm taller every year.",
  "Some fireflies flash light in perfect unison with each other.",
  "The blue whale's heart alone can weigh as much as a small car.",
  "Ants never sleep.",
  "A rhinoceros' horn is made of the same material as human hair — keratin.",
  "Saturn would float in water if you had a big enough bathtub.",
  "The first computer 'bug' was an actual moth stuck in a machine.",
  "Some spiders can 'fly' by releasing silk into the wind, called ballooning.",
  "The tallest waterfall in the world is Angel Falls in Venezuela.",
  "A group of owls is called a parliament.",
  "Sea stars can regrow an entire arm if it's lost.",
  "Chocolate was once used as currency by the Aztecs.",
  "There's a planet made mostly of diamond, discovered by astronomers.",
  "Some bamboo plants can grow almost a meter in a single day.",
  "Frogs can breathe through their skin.",
  "Bats always turn left when leaving a cave.",
  "The Great Barrier Reef is the largest living structure on Earth.",
  "An adult human body has about 37 trillion cells.",
  "A single bolt of lightning can strike the same place twice — or more.",
  "Peacocks are actually the male; females are called peahens.",
  "The moon has moonquakes, just like Earth has earthquakes.",
  "A day on Mercury lasts almost 59 Earth days.",
  "Some plants, like the Venus flytrap, can count how many times they're touched.",
  "The largest snowflake ever recorded was about 38 cm wide.",
  "Reindeer eyes change color with the seasons.",
  "There is a species of jellyfish called the 'immortal jellyfish.'",
  "Some ants can carry objects 50 times their own body weight.",
  "The longest living tree on record is over 5,000 years old.",
  "Rats laugh when they are tickled — but at a pitch humans can't hear.",
  "A hippopotamus can run faster than a human on land.",
  "The Amazon Rainforest produces about 20% of the world's oxygen.",
  "Some birds sleep with half their brain awake to stay alert for predators.",
  "The word 'set' has the most different meanings of any English word.",
  "A group of jellyfish is called a smack.",
  "Squids have a doughnut-shaped brain.",
  "Mars has the largest volcano in the solar system.",
  "Sloths can hold their breath longer than dolphins can.",
  "Wombats can run up to 40 km/h in short bursts.",
  "The oldest known living animal was a clam over 500 years old.",
  "Camels have three eyelids to protect against sand.",
  "The first alarm clock could only ring at 4 a.m.",
  "Space is completely silent because there is no air to carry sound.",
  "A group of hedgehogs is called an array.",
  "There's a lake in India that turns pink during certain seasons.",
  "Baby elephants suck their trunks for comfort, like a thumb.",
  "Termites can outnumber humans by a huge amount on Earth.",
  "It never rains on the summit of Mount Everest — only snow.",
  "Some species of turtle can live over 100 years.",
  "The longest recorded lightning bolt stretched over 700 km.",
  "A giant squid's eye can be as large as a basketball.",
  "The Pacific Ocean is larger than all landmasses combined.",
  "A group of rhinos is called a crash.",
  "Tigers have striped skin, not just striped fur.",
  "There are more trees on Earth than stars in the Milky Way.",
  "Some ducks have waterproof feathers thanks to natural oil.",
  "The fastest land animal is the cheetah, reaching over 100 km/h.",
  "Every year, millions of tons of dust from the Sahara reach the Amazon.",
  "The narwhal's 'horn' is actually a long tooth.",
  "Some species of frogs can freeze solid in winter and thaw out alive in spring.",
  "The first photograph ever taken required an 8-hour exposure.",
  "A group of foxes is called a skulk or a leash.",
  "Mount Kilimanjaro is the tallest freestanding mountain in the world.",
  "Some jellyfish glow in the dark through bioluminescence.",
  "A blue whale's heartbeat can be detected from over a mile away.",
  "The Great Barrier Reef can be seen from space.",
  "Ostrich eyes are bigger than their brains.",
  "There are more possible iterations of a shuffled deck of cards than atoms on Earth.",
  "A single teaspoon of a neutron star would weigh about 6 billion tons.",
  "Some species of ants can farm fungus for food.",
  "Emperor penguins can dive deeper than 500 meters.",
  "Bees communicate directions to flowers using a special waggle dance.",
  "There's a tree in Africa called the baobab that can store water in its trunk.",
  "The Milky Way galaxy is on a collision course with Andromeda — in billions of years.",
  "Some species of shrimp can create a snap loud enough to stun prey.",
  "A newborn kangaroo is about the size of a jellybean.",
  "Sound travels about four times faster in water than in air.",
  "Jupiter has the shortest day of all the planets, despite its huge size.",
  "The longest bridge in the world crosses more than 160 km.",
  "There's a species of ant that explodes to defend its colony.",
  "The blue-ringed octopus is one of the most venomous animals despite its tiny size.",
  "A group of larks is called an exaltation.",
  "Some deserts are cold, like the Gobi Desert in winter.",
  "The world's oldest recorded joke dates back nearly 4,000 years.",
  "A hummingbird can fly backward — the only bird that can.",
  "There's a species of jellyfish, the box jellyfish, with 24 eyes.",
  "Some clouds can look like a stack of pancakes, called lenticular clouds.",
  "The tallest tree in the world is a redwood over 115 meters tall.",
  "A crocodile's stomach contains stones to help it digest food.",
  "There's a volcano in Indonesia known for its blue flames at night.",
  "The world's deepest point is the Mariana Trench in the Pacific Ocean.",
  "Some spiders can survive underwater for hours using a bubble of air.",
  "Bats are the only mammals capable of true flight.",
  "There is a rare weather event called a 'fire rainbow.'",
  "The longest recorded flight without landing was made by a bar-tailed godwit bird.",
  "Some snowflakes can fall at speeds close to 1.5 meters per second.",
  "A group of frogs is called an army.",
  "There's a fish that can climb waterfalls using its mouth like a suction cup.",
  "The world's largest living organism is a fungus in Oregon, USA.",
  "Some plants glow faintly due to natural bioluminescent compounds.",
  "A group of jellyfish stinging together is sometimes called a bloom.",
  "The coldest temperature ever recorded on Earth was in Antarctica.",
  "There's a type of lizard that can run across water.",
  "A blue whale calf gains about 90 kg per day drinking its mother's milk.",
  "Some birds can sleep while flying, like the frigatebird.",
  "The longest total solar eclipse can last just over 7 minutes.",
  "There's a species of shark that glows in the dark.",
  "A single lightning strike can heat the air to 30,000 Kelvin.",
  "Some species of lobster can live over 100 years.",
  "The world's tallest geyser can shoot water over 100 meters high.",
  "A group of toads is called a knot.",
  "There's a desert ant that can navigate home by counting its own steps.",
  "The largest rainforest in the world is the Amazon, spanning nine countries.",
  "Some caterpillars taste like the leaves they eat, to fool predators.",
  "A group of whales is called a pod.",
  "There's a bird called the lyrebird that can imitate almost any sound it hears.",
  "The Earth's rotation is very slowly slowing down over millions of years.",
  "Some plants can survive being frozen and thaw out unharmed.",
  "A group of eagles is called a convocation.",
  "There's a species of octopus that can walk on two arms across the seafloor.",
  "The largest known crater on Earth is buried in Antarctica.",
  "Some fish, like the mudskipper, can survive out of water for hours.",
  "A group of lions is called a pride.",
  "There's a type of coral that can live for thousands of years.",
  "The world's smallest mammal is the bumblebee bat.",
  "Some birds build nests using spider silk to bind materials together.",
  "A group of geese on the ground is called a gaggle, but a skein in flight.",
  "There's a fish called the pufferfish that can inflate to several times its size.",
  "The largest canyon in the solar system is on Mars, called Valles Marineris.",
  "Some species of beetles are stronger than any other animal relative to their size.",
  "A group of bears is called a sloth or sleuth.",
  "There's a snake that can glide through the air between trees.",
  "The world's largest salt flat is in Bolivia and turns into a giant mirror when wet.",
  "Some plants can trap and digest insects for extra nutrients.",
  "A group of turtles is called a bale.",
  "There's a fish that produces its own light to attract prey in the deep sea.",
  "The largest glacier on Earth is in Antarctica, called the Lambert Glacier.",
  "Some insects can survive being frozen solid during winter.",
  "A group of storks is called a muster.",
  "There's a species of ant that can build living bridges out of their own bodies.",
  "The tallest active volcano in the world is Ojos del Salado in South America.",
  "Some birds can see ultraviolet light, invisible to human eyes.",
  "A group of hawks is called a kettle when circling in the sky.",
  "There's a jellyfish so large its tentacles can stretch over 30 meters.",
  "The largest hot desert in the world is the Sahara.",
  "Some fish can produce electric shocks to stun prey, like the electric eel.",
  "A group of swans is called a bevy or a wedge in flight.",
  "There's a plant called the corpse flower that smells like rotting meat when it blooms.",
  "The world's largest active volcano is Mauna Loa in Hawaii.",
  "Some crabs can regrow a lost claw over several molts.",
  "A group of dolphins is called a pod.",
  "There's a species of octopus that mimics other sea creatures to hide from predators.",
  "The longest mountain range on Earth is actually underwater — the Mid-Atlantic Ridge.",
  "Some birds migrate thousands of kilometers every year without getting lost.",
  "A group of parrots is called a pandemonium.",
  "There's a tree that can live for over 4,800 years, called Methuselah.",
  "The largest freshwater lake by volume is Lake Baikal in Russia.",
  "Some snakes can sense heat from prey using special pits on their face.",
  "A group of squirrels is called a scurry.",
  "There's a fish that can live both in water and walk briefly on land.",
  "The tallest sand dunes in the world are found in Iran and can reach 500 meters.",
  "Some birds of prey can spot small prey from over a kilometer away.",
  "A group of otters floating together is called a raft.",
  "There's a beetle that can survive being run over by a car.",
  "The largest coral reef system is the Great Barrier Reef in Australia.",
  "Some plants release their seeds by launching them like tiny catapults.",
  "A group of vultures circling is called a kettle, and resting is called a committee.",
  "There's a shrimp with a punch so fast it can boil the water around it briefly.",
  "The largest river by discharge volume is the Amazon River.",
  "Some geckos can walk upside down on glass thanks to microscopic foot hairs.",
  "A group of ravens is called an unkindness.",
  "There's a moth that drinks the tears of sleeping animals for nutrients.",
  "The tallest waterfall system in Africa is Tugela Falls.",
  "Some plants can 'talk' to each other through underground fungal networks.",
  "A group of moles is called a labor.",
  "There's a fish, the anglerfish, that uses a glowing lure to catch prey.",
  "The world's largest hot spring is the Frying Pan Lake in New Zealand.",
  "Some insects can lift many times their own body weight.",
  "A group of woodpeckers is called a descent.",
  "There's a plant that can move its leaves fast enough to see, the sensitive plant.",
  "The longest cave system in the world is Mammoth Cave in the United States.",
  "Some birds use tools, like crows bending wire to reach food.",
  "A group of herons is called a siege.",
  "There's a fish that changes color to match its surroundings, like a chameleon.",
  "The deepest cave on Earth is Veryovkina Cave in Georgia (country).",
  "Some plants bloom only once every several years, like the century plant.",
  "A group of hyenas is called a cackle.",
  "There's a spider that builds a web shaped like a wheel with spokes.",
  "The tallest tsunami ever recorded reached over 500 meters high.",
  "Some birds can fly nonstop for several days without resting.",
  "A group of jellyfish drifting together can stretch over a wide area of ocean.",
  "There's a fungus that can control the behavior of the ants it infects.",
  "The oldest living tree species is the Ginkgo biloba, dating back millions of years.",
  "Some fish can 'walk' along the ocean floor using their fins like legs.",
  "A group of crabs is called a cast.",
  "There's a bird, the kiwi, that lays an egg nearly a quarter of its own body weight.",
  "The tallest lighthouse in the world stands in Saudi Arabia.",
  "Some plants absorb sunlight so efficiently they barely need any water.",
  "A group of badgers is called a cete.",
  "There's a jellyfish that can turn itself back into a baby form to avoid death.",
  "The longest river in the world is the Nile, stretching over 6,600 km.",
  "Some caterpillars can spin silk strong enough to be used in textiles.",
  "A group of ferrets is called a business.",
  "There's a bird, the albatross, that can glide for hours without flapping its wings.",
  "The tallest waterfall in North America is Yosemite Falls.",
  "A group of zebras is called a dazzle.",
  "There's a beetle called the diving beetle that carries its own air bubble underwater.",
  "The tallest active geyser field in the world is in Yellowstone National Park.",
  "Some frogs can change color depending on their mood or temperature.",
  "A group of jellyfish is sometimes called a fluther.",
  "There's a tree frog that can survive falls from great heights without injury.",
  "The largest owl in the world is the Blakiston's fish owl.",
  "Some plants produce their own natural antifreeze to survive frost.",
  "A group of monkeys is called a troop.",
  "There's a fish called the flying fish that can glide above the ocean's surface.",
  "The largest bat in the world is the giant golden-crowned flying fox.",
  "Some insects can walk on water using surface tension, like water striders.",
  "A group of cheetahs is called a coalition.",
  "There's a plant, the touch-me-not, whose seed pods burst open when touched.",
  "The largest species of turtle is the leatherback sea turtle.",
  "Some birds build nests that hang like pouches from tree branches.",
  "A group of giraffes is called a tower.",
  "There's a fish, the archerfish, that shoots jets of water to knock down insects.",
  "The longest snake ever recorded was a reticulated python over 6 meters long.",
  "Some plants can survive in nearly pure rock with almost no soil.",
  "A group of leopards is called a leap.",
  "There's a bird, the hoatzin, whose chicks have claws on their wings.",
  "The smallest fish in the world is smaller than a grain of rice."
];

const DAILY_CONTENT_ANCHOR_MS = Date.UTC(2026, 0, 1, 0, 0, 0); // arbitrary fixed anchor
const WIB_OFFSET_MS = 7 * 60 * 60 * 1000; // UTC+7, Western Indonesia Time

function dailyContentIndex(length) {
  const wibNow = Date.now() + WIB_OFFSET_MS;
  const wibAnchor = DAILY_CONTENT_ANCHOR_MS + WIB_OFFSET_MS;
  const daysSinceAnchor = Math.floor((wibNow - wibAnchor) / 86400000);
  return ((daysSinceAnchor % length) + length) % length;
}

window.AIGDailyContent = {
  getWordOfDay() {
    const [word, meaning] = WORDS_OF_DAY[dailyContentIndex(WORDS_OF_DAY.length)];
    return { word, meaning };
  },
  getFunFact() {
    return FUN_FACTS[dailyContentIndex(FUN_FACTS.length)];
  }
};
